SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigExtension
SilverStripe\Forms\GridField\GridField:
  extensions:
    - GridFieldExtension
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - mysite/cms-assets/style.css
