---
Name: mysiteroutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'data/config.json': DataConfig_Controller
    'data/home.json': DataHome_Controller
    'data/classes.json': DataClasses_Controller
    'data/classes//$VenueID/$ClassCategoryPage!': DataClasses_Controller
    'data/faq.json': DataFAQ_Controller
