---
Name: mysiteroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'config.json': DataConfigController
    'home.json': DataHomeController
    'classes.json': DataClassesController
    'classes//$VenueID/$ClassCategoryPage!': DataClassesController
    'faq.json': DataFAQController
    'about-us.json': DataAboutUsController
    'contact-us.json': DataContactUsController
