---
Name: mysiteroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'data/config.json': DataConfigController
    'data/home.json': DataHomeController
    'data/classes.json': DataClassesController
    'data/classes//$VenueID/$ClassCategoryPage!': DataClassesController
    'data/faq.json': DataFAQController
    'data/about-us.json': DataAboutUsController
    'data/contact-us.json': DataContactUsController
